### ISSUE TITLE
Indentation in Python code

### ISSUE THREAD

**Issue by Qu3tzal** [SeimuPVE/DI4-UnsupervisedLearning#1]
On utilise des espaces (combien ?) ou des tabulations pour faire l'indentation dans le code Python ?
Parce que là tu as utilisé des espaces et moi des tabulations, donc c'est un peu embêtant quand on doit toucher au code de l'autre.

**Comment by SeimuPVE** [comment]
Go utiliser des tabs, les espaces ça doit venir du code de l'exemple j'utilise pas ça sinon. T'as le droit de virer les anciens espaces pour les remplacer par des tabs si ça te dérange ;)

**Comment by Qu3tzal** [comment]
Ok ça roule. ça me dérange pas mais quand il fallu que j'ajoute une info dans tmp_scripts j'ai du C/C les espaces
